[package]
name = "frede/resource-gathering-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.6.0"
Cmdr = "evaera/cmdr@1.12.0"
Janitor = "howmanysmall/janitor@1.15.6"
Signal = "sleitnick/signal@2.0.1"
ProfileService = "surnautica/profileservice@1.0.0"
Promise = "evaera/promise@4.0.0"
gameanalytics-sdk = "gameanalytics/gameanalytics-sdk@2.2.2"
moonlite = "maximumadhd/moonlite@0.9.0"
FormatNumber = "kumarion/formatnumber@0.0.1"
